import React, { useEffect, useMemo, useState } from 'react';
import * as I from 'lucide-react';
import { request, login } from './api.js';
import PublicSite from './PublicSite.jsx';

const NAV = [
  ['Command Center', I.LayoutDashboard], ['Assistant', I.Sparkles], ['Matters', I.BriefcaseBusiness], ['Clients', I.ContactRound],
  ['Vault', I.FolderLock], ['Research', I.LibraryBig], ['Drafting', I.FilePenLine], ['Document Review', I.ScanText], ['Templates', I.LayoutTemplate],
  ['Contracts', I.FileCheck2], ['Playbooks', I.BookMarked], ['Agents', I.Bot], ['Tasks', I.ListChecks],
  ['Calendar', I.CalendarDays], ['Conflict Check', I.ShieldAlert], ['Client Portal', I.Users], ['Early Access', I.Megaphone], ['Settings', I.Settings],
];

function Brand(){return <div className="brand"><div className="brand-main">Rafi</div><div className="brand-sub">legal assist</div></div>}
function Pill({children,tone=''}){return <span className={`pill ${tone}`}>{children}</span>}
function Btn({children,secondary=false,ghost=false,...props}){return <button className={`btn ${secondary?'secondary':''} ${ghost?'ghost':''}`} {...props}>{children}</button>}
function Card({children,className=''}){return <section className={`card ${className}`}>{children}</section>}
function Empty({title,body}){return <div className="empty"><I.CircleDashed/><b>{title}</b><span>{body}</span></div>}
function PageTitle({eyebrow,title,sub,action}){return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{sub&&<p className="sub">{sub}</p>}</div>{action&&<div className="head-actions">{action}</div>}</div>}
function fmtDate(v){if(!v)return '—';try{return new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}catch{return v}}
function fmtTime(v){if(!v)return '';try{return new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}catch{return ''}}

function Login({onLogin}){
  const [email,setEmail]=useState('admin@rafi.app'),[password,setPassword]=useState('ChangeMe123!'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{await login(email,password);await onLogin()}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <div className="login-shell"><div className="login-panel"><Brand/><div className="eyebrow">Canadian legal intelligence</div><h1>Run the matter.<br/>Not just the prompt.</h1><p>Rafi connects evidence, claims, authorities, deadlines, client work and firm playbooks into a reviewable legal workspace.</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<Btn disabled={busy}>{busy?'Signing in…':'Enter secure workspace'} <I.ArrowRight size={15}/></Btn></form><small>Demo: admin@rafi.app · ChangeMe123!</small></div><div className="login-art"><div className="mesh mesh-a"/><div className="mesh mesh-b"/><div className="quote">“Rafi doesn't just answer.<br/>Rafi shows its work.”</div></div></div>
}

function CommandCenter({data,openMatter,go}){
  const m=data?.metrics||{};
  return <><PageTitle eyebrow="Matter operating system" title="Command Center" sub="What changed, what conflicts, what is due, and what needs lawyer attention across your matters." action={<Btn onClick={()=>go('Matters')}><I.Network size={15}/> Open matter intelligence</Btn>}/>
    <div className="metric-grid">
      <Card><span className="metric-label">Active matters</span><div className="bigmetric">{m.active_matters||0}</div><small className="muted">Matter-centered workspaces</small></Card>
      <Card><span className="metric-label">Evidence conflicts</span><div className="bigmetric">{m.contradictions||0}</div><small className="muted">Source contradictions requiring review</small></Card>
      <Card><span className="metric-label">Open information gaps</span><div className="bigmetric">{m.open_gaps||0}</div><small className="muted">Questions or documents to confirm</small></Card>
      <Card><span className="metric-label">Verified corpus</span><div className="bigmetric">{m.corpus||0}</div><small className="muted">Curated / imported legal references</small></Card>
    </div>
    <div className="grid32 topgap"><Card><div className="card-title"><span>Matters requiring attention</span><Pill>Live context</Pill></div><div className="attention-list">{(data?.attention||[]).map(x=><button className="attention attention-button" key={x.id} onClick={()=>openMatter(x.id)}><div><b>{x.title}</b><small>{x.stage} · next deadline {fmtDate(x.deadline)}</small></div><div className="risk"><span style={{width:`${Math.round((x.risk||0)*100)}%`}}/><small>{Math.round((x.risk||0)*100)} risk</small></div></button>)}</div></Card>
      <Card><div className="card-title"><span>AI matter layer</span><Pill tone="purple">Differentiator</Pill></div><div className="stackstats"><div><b>{m.matter_claims||0}</b><span>connected claims</span></div><div><b>{m.documents||0}</b><span>matter documents</span></div><div><b>{m.hours_saved_estimate||0}h</b><span>estimated work assisted</span></div></div><p className="muted">Rafi's value is the connected legal workflow: evidence → claims → issues → authorities → deadlines → action.</p></Card></div>
    <div className="grid2 topgap"><Card><div className="card-title"><span>What changed</span><Pill>Digest</Pill></div>{(data?.digests||[]).slice(0,6).map(d=><button className="digest" key={d.id} onClick={()=>openMatter(d.matter_id)}><I.Activity size={15}/><div><b>{d.matter_title}</b><span>{d.summary}</span><small>{fmtDate(d.created_at)} · {d.change_type.replaceAll('_',' ')}</small></div></button>)}</Card><Card><div className="card-title"><span>Upcoming</span><Pill>Recorded sources</Pill></div>{(data?.upcoming||[]).map(e=><div className="deadline-row" key={e.id}><div className="datebox"><b>{new Date(e.start_at).getDate()}</b><span>{new Date(e.start_at).toLocaleString('default',{month:'short'})}</span></div><div><b>{e.title}</b><small>{fmtTime(e.start_at)} {e.location?`· ${e.location}`:''}</small></div></div>)}</Card></div>
  </>
}

function Matters({items,openMatter,reload}){
  const [show,setShow]=useState(false),[form,setForm]=useState({title:'',matter_number:'',practice_area:'Employment',jurisdiction:'Ontario, Canada'}),[busy,setBusy]=useState(false);
  async function create(e){e.preventDefault();setBusy(true);try{const m=await request('/matters',{method:'POST',body:JSON.stringify(form)});setShow(false);await reload();openMatter(m.id)}finally{setBusy(false)}}
  return <><PageTitle eyebrow="Matter intelligence" title="Matters" sub="Each matter is a persistent evidence, research, deadline and workflow context—not a disposable chat." action={<Btn onClick={()=>setShow(true)}><I.Plus size={14}/> New matter</Btn>}/><div className="cards3">{items.map(m=><button className="matter-card" key={m.id} onClick={()=>openMatter(m.id)}><div className="matter-top"><Pill>{m.practice_area}</Pill><I.ArrowUpRight size={16}/></div><h3>{m.title}</h3><p>{m.summary||'No summary yet.'}</p><div className="matter-meta"><span>{m.matter_number}</span><span>{m.stage}</span><span>{fmtDate(m.next_deadline)}</span></div><div className="riskbar"><span style={{width:`${Math.round((m.risk_score||0)*100)}%`}}/></div></button>)}</div>{show&&<div className="modal-back"><div className="modal"><div className="modal-head"><h3>Create matter</h3><button className="iconbtn" onClick={()=>setShow(false)}><I.X/></button></div><form className="form" onSubmit={create}><label>Matter title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Matter number<input required value={form.matter_number} onChange={e=>setForm({...form,matter_number:e.target.value})}/></label><label>Practice area<input value={form.practice_area} onChange={e=>setForm({...form,practice_area:e.target.value})}/></label><label>Jurisdiction<input value={form.jurisdiction} onChange={e=>setForm({...form,jurisdiction:e.target.value})}/></label><Btn disabled={busy}>{busy?'Creating…':'Create matter'}</Btn></form></div></div>}</>
}

function EvidenceDrawer({target,onClose}){
  const [page,setPage]=useState(null),[error,setError]=useState('');
  useEffect(()=>{if(!target)return;request(`/documents/${target.document_id}/page/${target.page_number||1}`).then(setPage).catch(e=>setError(e.message))},[target]);
  if(!target)return null;
  return <div className="drawer-back" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><div className="eyebrow">Source evidence</div><h2>{page?.name||target.label||'Evidence'}</h2></div><button className="iconbtn" onClick={onClose}><I.X/></button></div><div className="source-meta"><Pill>Page {target.page_number||1}</Pill><Pill tone={target.relationship==='contradicts'?'danger':'good'}>{target.relationship||'source'}</Pill></div>{error&&<div className="error">{error}</div>}<blockquote>{target.quote||'Click-through source text.'}</blockquote><div className="page-text">{page?.text||'Loading source page…'}</div><div className="drawer-note"><I.ShieldCheck size={16}/> Evidence links reference stored source text. Legal significance still requires lawyer review.</div></aside></div>
}

function MatterGraph({graph,onEvidence}){
  const nodes=graph?.nodes||[],edges=graph?.edges||[];
  const order=['claim','evidence','issue','authority']; const xMap={claim:110,evidence:370,issue:635,authority:900};
  const pos={}; let maxCount=1;
  order.forEach(type=>{const list=nodes.filter(n=>n.type===type);maxCount=Math.max(maxCount,list.length);list.forEach((n,i)=>{pos[n.id]={x:xMap[type],y:70+i*92}})});
  const h=Math.max(440,90+maxCount*92);
  function click(n){if(n.type==='evidence')onEvidence(n);else if(n.type==='authority'&&n.url)window.open(n.url,'_blank','noopener,noreferrer')}
  return <div className="graph-wrap"><div className="graph-headings"><span>Claims</span><span>Evidence</span><span>Legal issues</span><span>Authorities</span></div><svg className="graph-svg" viewBox={`0 0 1020 ${h}`} role="img" aria-label="Matter intelligence graph"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="#6d557e"/></marker></defs>{edges.map((e,i)=>{const a=pos[e.source],b=pos[e.target];if(!a||!b)return null;return <g key={i}><path d={`M${a.x+85},${a.y} C${a.x+150},${a.y} ${b.x-150},${b.y} ${b.x-85},${b.y}`} className={`edge ${e.relation==='contradicts'?'edge-danger':''}`} markerEnd="url(#arrow)"/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2-6} className="edge-label">{e.relation?.replaceAll('_',' ')}</text></g>})}{nodes.map(n=>{const p=pos[n.id];if(!p)return null;const label=(n.label||'').length>25?(n.label.slice(0,24)+'…'):n.label;return <g key={n.id} className={`graph-node node-${n.type}`} transform={`translate(${p.x-88},${p.y-31})`} onClick={()=>click(n)}><rect width="176" height="62" rx="12"/><text x="14" y="24" className="node-label">{label}</text><text x="14" y="44" className="node-sub">{n.subtitle||n.type}</text></g>})}</svg></div>
}

function MatterWorkspace({matterId,onBack,reloadGlobal}){
  const [intel,setIntel]=useState(null),[detail,setDetail]=useState(null),[tab,setTab]=useState('Overview'),[busy,setBusy]=useState(false),[evidence,setEvidence]=useState(null),[brief,setBrief]=useState(''),[error,setError]=useState('');
  async function load(){setError('');try{const [i,d]=await Promise.all([request(`/matters/${matterId}/intelligence`),request(`/matters/${matterId}`)]);setIntel(i);setDetail(d)}catch(e){setError(e.message)}}
  useEffect(()=>{load()},[matterId]);
  async function rebuild(){setBusy(true);try{setIntel(await request(`/matters/${matterId}/intelligence/rebuild`,{method:'POST'}));await reloadGlobal()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function makeBrief(){setBusy(true);try{const d=await request(`/matters/${matterId}/brief`,{method:'POST'});setBrief(d.brief);setTab('Brief')}catch(e){setError(e.message)}finally{setBusy(false)}}
  if(error)return <><Btn secondary onClick={onBack}><I.ArrowLeft size={14}/> Matters</Btn><div className="error topgap">{error}</div></>;
  if(!intel)return <div className="loading-inline"><I.LoaderCircle className="spin"/> Building matter view…</div>;
  const s=intel.summary,m=intel.matter;
  const tabs=['Overview','Claims & Evidence','Chronology','Issues & Authorities','Gaps & Actions','Deadlines','Brief'];
  return <><div className="matter-hero"><button className="backlink" onClick={onBack}><I.ArrowLeft size={14}/> All matters</button><div className="matter-hero-row"><div><div className="eyebrow">{m.matter_number} · {m.jurisdiction}</div><h1>{m.title}</h1><p>{m.summary}</p></div><div className="head-actions"><Btn secondary onClick={makeBrief} disabled={busy}><I.FileText size={14}/> Generate brief</Btn><Btn onClick={rebuild} disabled={busy}><I.RefreshCw size={14} className={busy?'spin':''}/> Refresh intelligence</Btn></div></div><div className="intel-kpis"><div><b>{s.facts}</b><span>key facts</span></div><div><b>{s.claims}</b><span>claims</span></div><div><b>{s.evidence_links}</b><span>evidence links</span></div><div className={s.contradictions?'warn':''}><b>{s.contradictions}</b><span>contradictions</span></div><div><b>{s.issues}</b><span>legal issues</span></div><div><b>{s.missing}</b><span>missing items</span></div><div><b>{s.deadlines}</b><span>deadlines</span></div></div></div>
    <div className="tabs">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
    {tab==='Overview'&&<div className="grid32"><Card className="graph-card"><div className="card-title"><span>Matter Intelligence Graph</span><Pill tone="good"><I.Link2 size={11}/> Source connected</Pill></div><p className="muted">Claims connect to source evidence, review issues, and retrieved Canadian authorities. Click evidence nodes to inspect the source page.</p><MatterGraph graph={intel.graph} onEvidence={setEvidence}/></Card><div className="side-stack"><Card><div className="card-title"><span>Latest change</span><Pill>Digest</Pill></div>{intel.digests?.[0]?<><h3 className="small-h3">{intel.digests[0].title}</h3><p className="muted">{intel.digests[0].summary}</p><small className="muted">{fmtDate(intel.digests[0].created_at)}</small></>:<Empty title="No digest" body="Refresh intelligence after adding evidence."/>}</Card><Card><div className="card-title"><span>Guardrails</span><I.ShieldCheck size={16}/></div><div className="guard"><span>Evidence-backed factual links</span><Pill tone="good">On</Pill></div><div className="guard"><span>Human review required</span><Pill tone="good">On</Pill></div><div className="guard"><span>Authority applicability</span><Pill>Lawyer review</Pill></div></Card></div></div>}
    {tab==='Claims & Evidence'&&<div className="claims-list">{intel.claims.map(c=>{const ev=intel.evidence.filter(e=>e.claim_id===c.id);return <Card key={c.id}><div className="claim-head"><div><Pill tone={c.status==='conflict'?'danger':'good'}>{c.status}</Pill><h3>{c.title}</h3></div><span className="confidence">{Math.round(c.confidence*100)}% extraction confidence</span></div><p className="claim-statement">{c.statement}</p><div className="evidence-grid">{ev.map(e=><button className={`evidence-card ${e.relationship}`} key={e.id} onClick={()=>setEvidence({...e,label:e.document_name})}><div><I.FileSearch size={15}/><b>{e.document_name}</b><Pill tone={e.relationship==='contradicts'?'danger':'good'}>{e.relationship}</Pill></div><small>Page {e.page_number}</small><p>“{e.quote}”</p><span>Open source <I.ArrowUpRight size={12}/></span></button>)}</div></Card>})}</div>}
    {tab==='Chronology'&&<Card><div className="card-title"><span>Evidence-linked chronology</span><Pill>{intel.facts.length} facts</Pill></div><div className="timeline">{intel.facts.map(f=><button key={f.id} className="timeline-row" onClick={()=>f.document_id&&setEvidence({document_id:f.document_id,page_number:f.page_number,quote:f.source_quote,relationship:'source'})}><div className="timeline-date">{f.event_date?fmtDate(f.event_date):'Undated'}</div><div className="timeline-dot"/><div><b>{f.statement}</b><small>{f.document_id?`Source document · p. ${f.page_number||1}`:'Matter record'} · {Math.round((f.confidence||0)*100)}% confidence</small></div></button>)}</div></Card>}
    {tab==='Issues & Authorities'&&<div className="cards3">{intel.issues.map(issue=><Card key={issue.id}><div className="card-title"><Pill>{issue.status}</Pill><span>{Math.round(issue.confidence*100)}%</span></div><h3>{issue.title}</h3><p className="muted">{issue.description}</p><div className="authority-list">{issue.authorities.map(a=><a key={a.id} className="authority" href={a.url||'#'} target="_blank" rel="noreferrer"><I.Scale size={15}/><div><b>{a.title}</b><span>{a.citation||'Reference'}</span><small>{a.verified?'✓ citation/source metadata verified':'Review source metadata'}</small></div><I.ExternalLink size={13}/></a>)}</div></Card>)}</div>}
    {tab==='Gaps & Actions'&&<div className="grid2"><Card><div className="card-title"><span>Missing information</span><Pill>{intel.missing_information.filter(x=>x.status==='open').length} open</Pill></div>{intel.missing_information.map(g=><div className="gap-row" key={g.id}><I.CircleHelp size={16}/><div><b>{g.description}</b><small>{g.priority} priority · {g.requested_from}</small></div><button onClick={async()=>{await request(`/missing-information/${g.id}`,{method:'PATCH',body:JSON.stringify({status:g.status==='open'?'resolved':'open'})});load()}}>{g.status==='open'?'Resolve':'Reopen'}</button></div>)}</Card><Card><div className="card-title"><span>Recommended next actions</span><Pill>Approval required</Pill></div>{intel.recommendations.map(r=><div className="action-row" key={r.id}><div className={`action-icon ${r.priority}`}><I.WandSparkles size={15}/></div><div><b>{r.title}</b><span>{r.rationale}</span><small>{r.action_type.replaceAll('_',' ')} · {r.priority}</small></div><button onClick={async()=>{await request(`/recommendations/${r.id}`,{method:'PATCH',body:JSON.stringify({status:r.status==='approved'?'proposed':'approved'})});load()}}>{r.status==='approved'?'Approved':'Approve'}</button></div>)}</Card></div>}
    {tab==='Deadlines'&&<Card><div className="card-title"><span>Recorded deadlines & events</span><Pill>Not AI-guessed</Pill></div>{intel.deadlines.map(d=><div className="deadline-row large" key={d.id}><div className="datebox"><b>{new Date(d.due_at).getDate()}</b><span>{new Date(d.due_at).toLocaleString('default',{month:'short'})}</span></div><div><b>{d.title}</b><small>{fmtDate(d.due_at)} · source: {d.source_type} · confidence {Math.round(d.confidence*100)}%</small></div></div>)}</Card>}
    {tab==='Brief'&&<Card><div className="card-title"><span>Lawyer-review matter brief</span><Pill>Draft</Pill></div>{brief?<pre className="research-answer">{brief}</pre>:<Empty title="No brief generated" body="Generate a matter brief from source-linked evidence, issues, gaps and deadlines."/>}</Card>}
    <EvidenceDrawer target={evidence} onClose={()=>setEvidence(null)}/>
  </>
}


function Clients({items,reload}){const [show,setShow]=useState(false),[form,setForm]=useState({name:'',email:'',company:'',phone:''});async function create(e){e.preventDefault();await request('/clients',{method:'POST',body:JSON.stringify(form)});setShow(false);reload()}return <><PageTitle eyebrow="Relationship management" title="Clients" sub="Keep client identity and matter relationships in the same tenant-scoped workspace." action={<Btn onClick={()=>setShow(true)}><I.Plus size={14}/> New client</Btn>}/><div className="cards3">{items.map(c=><Card key={c.id}><div className="client-avatar">{c.name?.[0]||'C'}</div><h3>{c.name}</h3><p className="muted">{c.company||'Individual client'}</p><div className="client-lines">{c.email&&<span><I.Mail size={13}/>{c.email}</span>}{c.phone&&<span><I.Phone size={13}/>{c.phone}</span>}</div></Card>)}</div>{show&&<div className="modal-back"><div className="modal"><div className="modal-head"><h3>Create client</h3><button className="iconbtn" onClick={()=>setShow(false)}><I.X/></button></div><form className="form" onSubmit={create}><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Company<input value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><Btn>Create client</Btn></form></div></div>}</>}

function Assistant({matters}){const [message,setMessage]=useState('Summarize the key issues and evidence conflicts in this matter.'),[matterId,setMatterId]=useState(matters[0]?.id||''),[out,setOut]=useState(null),[busy,setBusy]=useState(false);async function run(){setBusy(true);try{setOut(await request('/ai/chat',{method:'POST',body:JSON.stringify({message,matter_id:matterId?Number(matterId):null,jurisdiction:'Ontario, Canada'})}))}catch(e){setOut({answer:`Error: ${e.message}`,sources:[]})}finally{setBusy(false)}}return <><PageTitle eyebrow="Source-grounded legal work" title="Ask Rafi" sub="Ask within a persistent matter context. Rafi retrieves authorized sources and keeps final judgment with counsel."/><div className="assistant-layout"><Card className="compose"><textarea value={message} onChange={e=>setMessage(e.target.value)}/><div className="composebar"><select value={matterId} onChange={e=>setMatterId(e.target.value)}><option value="">No matter</option>{matters.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select><Btn onClick={run} disabled={busy}>{busy?'Working…':'Ask Rafi'} <I.Send size={13}/></Btn></div></Card><Card className="answer">{out?<><pre>{out.answer}</pre><div className="sources"><b>Retrieved sources</b>{(out.sources||[]).map((s,i)=><div className="source" key={i}><span>S{i+1}</span><div><b>{s.title}</b><small>{s.citation||s.source_type||'source'} {s.verified?'· verified metadata':''}</small></div></div>)}</div></>:<Empty title="Matter-aware assistance" body="Choose a matter so Rafi can preserve its context rather than starting from a blank chat."/>}</Card></div></>}

function Vault({docs,matters,reload,openMatter}){const [file,setFile]=useState(null),[matter,setMatter]=useState(''),[busy,setBusy]=useState(false);async function upload(){if(!file)return;setBusy(true);const fd=new FormData();fd.append('file',file);if(matter)fd.append('matter_id',matter);fd.append('category','Evidence');try{await request('/documents/upload',{method:'POST',body:fd});await reload();if(matter)openMatter(Number(matter))}finally{setBusy(false)}}return <><PageTitle eyebrow="Governed evidence workspace" title="Vault" sub="Uploading a document to a matter automatically refreshes its evidence-linked intelligence graph."/><Card><div className="uploadbar"><input type="file" onChange={e=>setFile(e.target.files?.[0])}/><select value={matter} onChange={e=>setMatter(e.target.value)}><option value="">General vault</option>{matters.map(m=><option value={m.id} key={m.id}>{m.title}</option>)}</select><Btn onClick={upload} disabled={!file||busy}>{busy?'Indexing…':'Upload & index'}</Btn></div></Card><div className="tablewrap topgap"><table><thead><tr><th>Document</th><th>Matter</th><th>Category</th><th>Version</th><th>Indexed</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td>{d.name}</td><td>{matters.find(m=>m.id===d.matter_id)?.title||'General'}</td><td>{d.category}</td><td>v{d.version}</td><td>{d.text_content?'Yes':'Metadata only'}</td></tr>)}</tbody></table></div></>}

function Research(){const [q,setQ]=useState('What authorities may be relevant to wrongful dismissal incentive compensation in Canada?'),[r,setR]=useState(null),[busy,setBusy]=useState(false);async function run(){setBusy(true);try{setR(await request('/research',{method:'POST',body:JSON.stringify({query:q,jurisdiction:'Ontario, Canada',top_k:8})}))}finally{setBusy(false)}}return <><PageTitle eyebrow="Verified Canadian sources" title="Research" sub="Retrieve first, synthesize second. Rafi is instructed not to manufacture authorities when the corpus is insufficient."/><div className="researchbar"><input value={q} onChange={e=>setQ(e.target.value)}/><Btn onClick={run} disabled={busy}>{busy?'Researching…':'Research'}</Btn></div>{r&&<div className="grid32"><Card><pre className="research-answer">{r.answer}</pre></Card><Card><div className="card-title"><span>Source ledger</span><Pill>{r.sources.length}</Pill></div>{r.sources.map((s,i)=><a className="authority" key={i} href={s.url||'#'} target="_blank" rel="noreferrer"><I.BookOpenCheck size={15}/><div><b>{s.title}</b><span>{s.citation||s.source_type}</span><small>{s.verified?'✓ verified metadata':'Review metadata'} · current to {s.current_to||'not recorded'}</small></div></a>)}</Card></div>}</>}

function Drafting({matters}){const [type,setType]=useState('client status update'),[facts,setFacts]=useState(''),[matter,setMatter]=useState(matters[0]?.id||''),[out,setOut]=useState(''),[busy,setBusy]=useState(false);async function run(){setBusy(true);try{const d=await request('/drafting/generate',{method:'POST',body:JSON.stringify({document_type:type,facts,matter_id:matter?Number(matter):null,jurisdiction:'Ontario, Canada'})});setOut(d.draft)}finally{setBusy(false)}}return <><PageTitle eyebrow="Reviewable work product" title="Drafting" sub="Matter context, unresolved contradictions and missing facts follow the draft instead of disappearing in a blank prompt."/><div className="grid2"><Card><label className="field">Matter<select value={matter} onChange={e=>setMatter(e.target.value)}><option value="">No matter</option>{matters.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><label className="field">Document type<input value={type} onChange={e=>setType(e.target.value)}/></label><label className="field">Verified facts<textarea value={facts} onChange={e=>setFacts(e.target.value)} placeholder="Only provide verified facts. Missing details will be marked for review."/></label><Btn onClick={run} disabled={busy}>{busy?'Drafting…':'Generate draft'}</Btn></Card><Card><div className="card-title"><span>Draft work product</span><Pill>Review required</Pill></div>{out?<pre className="research-answer">{out}</pre>:<Empty title="Ready to draft" body="Rafi does not intentionally invent authorities, names, dates or procedural requirements."/>}</Card></div></>}

function DocumentReview(){const [text,setText]=useState(''),[kind,setKind]=useState('issue_spotting'),[out,setOut]=useState(''),[busy,setBusy]=useState(false);async function run(){setBusy(true);try{const d=await request('/documents/analyze-text',{method:'POST',body:JSON.stringify({text,analysis_type:kind,jurisdiction:'Ontario, Canada'})});setOut(d.analysis)}finally{setBusy(false)}}return <><PageTitle eyebrow="Evidence-aware review" title="Document Review" sub="Analyze text for issues, dates, obligations, inconsistencies, missing information and counsel questions."/><div className="grid2"><Card><label className="field">Analysis<select value={kind} onChange={e=>setKind(e.target.value)}><option value="issue_spotting">Issue spotting</option><option value="chronology">Chronology</option><option value="obligations">Obligations</option><option value="risk_review">Risk review</option><option value="compare_position">Position analysis</option></select></label><textarea className="contract" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste extracted document text here, or upload a file to Vault."/><Btn onClick={run} disabled={busy||!text}>{busy?'Analyzing…':'Analyze'}</Btn></Card><Card>{out?<pre className="research-answer">{out}</pre>:<Empty title="Document intelligence" body="Separate document facts from legal inference and keep important conclusions reviewable."/>}</Card></div></>}

function Contracts({playbooks}){const [text,setText]=useState('SERVICE AGREEMENT\nThe customer may terminate only with 90 days written notice. The supplier may increase fees at renewal by written notice.'),[pb,setPb]=useState(playbooks[0]?.id||''),[res,setRes]=useState('');async function run(){const d=await request('/contracts/review',{method:'POST',body:JSON.stringify({text,playbook_id:pb?Number(pb):null,jurisdiction:'Ontario, Canada'})});setRes(d.analysis)}return <><PageTitle eyebrow="Contract intelligence" title="First-pass review" sub="Triage against your firm's persistent playbook rather than recreating instructions in every prompt."/><div className="grid2"><Card><label className="field">Firm playbook<select value={pb} onChange={e=>setPb(e.target.value)}><option value="">No playbook</option>{playbooks.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><textarea className="contract" value={text} onChange={e=>setText(e.target.value)}/><Btn onClick={run}>Review contract</Btn></Card><Card><div className="card-title"><span>Issue list</span><Pill>Draft</Pill></div>{res?<pre className="research-answer">{res}</pre>:<Empty title="Ready to review" body="Compare contract text against institutional firm rules."/>}</Card></div></>}

function Playbooks({items,reload}){const [show,setShow]=useState(false),[form,setForm]=useState({name:'',practice_area:'General',description:'',rules:''});async function create(e){e.preventDefault();await request('/playbooks',{method:'POST',body:JSON.stringify({...form,rules:form.rules.split('\n').filter(Boolean)})});setShow(false);reload()}return <><PageTitle eyebrow="Institutional knowledge" title="Firm Playbooks" sub="Store how your firm wants legal work reviewed so the workflow survives beyond any single chat thread." action={<Btn onClick={()=>setShow(true)}><I.Plus size={14}/> New playbook</Btn>}/><div className="cards3">{items.map(p=><Card key={p.id}><Pill>{p.practice_area}</Pill><h3>{p.name}</h3><p className="muted">{p.description}</p><div className="rule-list">{(p.rules||[]).map((r,i)=><div key={i}><I.Check size={12}/>{r}</div>)}</div></Card>)}</div>{show&&<div className="modal-back"><div className="modal"><div className="modal-head"><h3>Create playbook</h3><button className="iconbtn" onClick={()=>setShow(false)}><I.X/></button></div><form className="form" onSubmit={create}><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Practice area<input value={form.practice_area} onChange={e=>setForm({...form,practice_area:e.target.value})}/></label><label>Description<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Rules — one per line<textarea value={form.rules} onChange={e=>setForm({...form,rules:e.target.value})}/></label><Btn>Create playbook</Btn></form></div></div>}</>}

function Agents({workflows,reload}){async function run(id){await request(`/workflows/${id}/run`,{method:'POST'});reload()}return <><PageTitle eyebrow="Workflow agents" title="Agents" sub="Repeatable multi-step legal work with explicit lawyer approval gates."/><div className="cards3">{workflows.map(w=><Card key={w.id}><div className="agenticon"><I.Bot/></div><h3>{w.name}</h3><p className="muted">{w.description}</p><div className="steps">{(w.steps||[]).map((s,i)=><span key={i}>{i+1}. {s}</span>)}</div><div className="row"><Pill>{w.runs} runs</Pill><Btn secondary onClick={()=>run(w.id)}>Run workflow</Btn></div></Card>)}</div></>}
function Tasks({tasks,reload}){async function toggle(id){await request(`/tasks/${id}/toggle`,{method:'PATCH'});reload()}return <><PageTitle eyebrow="Execution" title="Tasks"/><Card>{tasks.map(t=><div className={`task ${t.status==='done'?'done':''}`} key={t.id}><button onClick={()=>toggle(t.id)}>{t.status==='done'?<I.CheckCircle2/>:<I.Circle/>}</button><div><b>{t.title}</b><small>{t.assigned_to||'Unassigned'} · {t.priority} priority</small></div>{t.due_at&&<Pill>{fmtDate(t.due_at)}</Pill>}</div>)}</Card></>}
function Calendar({events}){async function connect(){try{const d=await request('/calendar/google/connect-url');window.location.href=d.url}catch(e){alert(e.message)}}return <><PageTitle eyebrow="Deadlines and events" title="Calendar" action={<Btn secondary onClick={connect}><I.CalendarSync size={15}/> Connect Google</Btn>}/><div className="cards3">{events.map(e=><Card key={e.id}><Pill>{fmtDate(e.start_at)}</Pill><h3>{e.title}</h3><p className="muted">{fmtTime(e.start_at)}</p></Card>)}</div></>}
function ConflictCheck(){const [q,setQ]=useState('Acme'),[r,setR]=useState(null);async function run(){setR(await request(`/conflicts?name=${encodeURIComponent(q)}`))}return <><PageTitle eyebrow="Risk control" title="Conflict Check" sub="Search clients, matters, opposing parties and counsel. Results still require professional review."/><div className="researchbar"><input value={q} onChange={e=>setQ(e.target.value)}/><Btn onClick={run}>Check</Btn></div>{r&&<Card><h3>Potential matches</h3><p>{r.clients.length} client match(es) · {r.matters.length} matter match(es)</p>{[...r.clients,...r.matters].map((x,i)=><div className="attention" key={i}><b>{x.name||x.title}</b><Pill>Review</Pill></div>)}</Card>}</>}
function Portal({matters}){return <><PageTitle eyebrow="Governed collaboration" title="Client Portal" sub="Matter-scoped collaboration foundation for shared files, messages and signatures."/><div className="cards3">{matters.map(m=><Card key={m.id}><Pill>{m.stage}</Pill><h3>{m.title}</h3><p className="muted">{m.matter_number}</p><div className="portal-actions"><span><I.FileText/> Shared files</span><span><I.MessageSquare/> Messages</span><span><I.PenLine/> Signatures</span></div></Card>)}</div></>}
function EarlyAccess(){
  const [data,setData]=useState(null),[error,setError]=useState('');
  useEffect(()=>{request('/growth/leads').then(setData).catch(e=>setError(e.message))},[]);
  if(error)return <><PageTitle eyebrow="Growth" title="Early Access"/><div className="error">{error}</div></>;
  if(!data)return <div className="loading-inline"><I.LoaderCircle className="spin"/> Loading early-access leads…</div>;
  return <><PageTitle eyebrow="Founder CRM" title="Early Access" sub="Website waitlist and demo requests are stored here so you can follow up without a third-party form service."/>
    <div className="metric-grid"><Card><span className="metric-label">Waitlist</span><div className="bigmetric">{data.summary.waitlist}</div><small className="muted">Early-access signups</small></Card><Card><span className="metric-label">Demo requests</span><div className="bigmetric">{data.summary.demo_requests}</div><small className="muted">Sales conversations requested</small></Card></div>
    <div className="topgap"><div className="card-title"><span>Demo requests</span><Pill>{data.demo_requests.length}</Pill></div><div className="tablewrap"><table><thead><tr><th>Date</th><th>Name</th><th>Organization</th><th>Role</th><th>Team</th><th>Practice</th><th>Email</th></tr></thead><tbody>{data.demo_requests.map(x=><tr key={x.id}><td>{fmtDate(x.created_at)}</td><td>{x.first_name} {x.last_name}</td><td>{x.organization}</td><td>{x.role||'—'}</td><td>{x.team_size||'—'}</td><td>{x.practice_area||'—'}</td><td>{x.work_email}</td></tr>)}</tbody></table></div></div>
    <div className="topgap"><div className="card-title"><span>Waitlist</span><Pill>{data.waitlist.length}</Pill></div><div className="tablewrap"><table><thead><tr><th>Date</th><th>Name</th><th>Organization</th><th>Role</th><th>Team</th><th>Email</th></tr></thead><tbody>{data.waitlist.map(x=><tr key={x.id}><td>{fmtDate(x.created_at)}</td><td>{x.full_name||'—'}</td><td>{x.organization||'—'}</td><td>{x.role||'—'}</td><td>{x.team_size||'—'}</td><td>{x.email}</td></tr>)}</tbody></table></div></div>
  </>
}

function Settings(){return <><PageTitle eyebrow="Administration" title="Settings"/><div className="grid2"><Card><h3>AI governance</h3><div className="guard"><span>Human review required</span><Pill tone="good">On</Pill></div><div className="guard"><span>Evidence provenance</span><Pill tone="good">On</Pill></div><div className="guard"><span>Default jurisdiction</span><Pill>Ontario, Canada</Pill></div></Card><Card><h3>Corpus policy</h3><p className="muted">Use authorized sources only. Rafi v3 includes curated editorial notes for real Canadian authorities plus an importer for federal Acts and regulations from the Justice Laws repository. It does not bulk-copy CanLII.</p></Card></div></>}
function Templates(){const [items,setItems]=useState([]);useEffect(()=>{request('/templates').then(setItems).catch(()=>{})},[]);return <><PageTitle eyebrow="Reusable work product" title="Templates"/><div className="cards3">{items.map(t=><Card key={t.id}><Pill>{t.category}</Pill><h3>{t.name}</h3><p className="muted">{t.description}</p></Card>)}</div></>}

function WorkspaceApp(){
  const [user,setUser]=useState(null),[page,setPage]=useState('Command Center'),[selectedMatter,setSelectedMatter]=useState(null),[data,setData]=useState(null),[matters,setMatters]=useState([]),[clients,setClients]=useState([]),[docs,setDocs]=useState([]),[tasks,setTasks]=useState([]),[events,setEvents]=useState([]),[workflows,setWorkflows]=useState([]),[playbooks,setPlaybooks]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState('');
  async function load(){try{const [me,d,m,c,do_,t,e,w,p]=await Promise.all([request('/auth/me'),request('/dashboard'),request('/matters'),request('/clients'),request('/documents'),request('/tasks'),request('/events'),request('/workflows'),request('/playbooks')]);setUser(me);setData(d);setMatters(m);setClients(c);setDocs(do_);setTasks(t);setEvents(e);setWorkflows(w);setPlaybooks(p)}catch{localStorage.removeItem('rafi_token');setUser(null)}finally{setLoading(false)}}
  useEffect(()=>{if(localStorage.getItem('rafi_token'))load();else setLoading(false)},[]);
  function openMatter(id){setSelectedMatter(id);setPage('Matters')}
  function go(p){setSelectedMatter(null);setPage(p)}
  const content=useMemo(()=>{
    if(page==='Matters'&&selectedMatter)return <MatterWorkspace matterId={selectedMatter} onBack={()=>setSelectedMatter(null)} reloadGlobal={load}/>;
    return ({
      'Command Center':<CommandCenter data={data} openMatter={openMatter} go={go}/>,Assistant:<Assistant matters={matters}/>,Matters:<Matters items={matters} openMatter={openMatter} reload={load}/>,Clients:<Clients items={clients} reload={load}/>,Vault:<Vault docs={docs} matters={matters} reload={load} openMatter={openMatter}/>,Research:<Research/>,Drafting:<Drafting matters={matters}/>,'Document Review':<DocumentReview/>,Templates:<Templates/>,Contracts:<Contracts playbooks={playbooks}/>,Playbooks:<Playbooks items={playbooks} reload={load}/>,Agents:<Agents workflows={workflows} reload={load}/>,Tasks:<Tasks tasks={tasks} reload={load}/>,Calendar:<Calendar events={events}/>,'Conflict Check':<ConflictCheck/>,'Client Portal':<Portal matters={matters}/>,'Early Access':<EarlyAccess/>,Settings:<Settings/>
    })[page]
  },[page,selectedMatter,data,matters,clients,docs,tasks,events,workflows,playbooks]);
  if(loading)return <div className="loading"><Brand/><I.LoaderCircle className="spin"/><span>Loading secure workspace…</span></div>;
  if(!user)return <Login onLogin={load}/>;
  return <div className="shell"><aside className="sidebar"><Brand/><button className="newthread" onClick={()=>go('Assistant')}><I.Plus size={16}/> <span>New thread</span></button><nav>{NAV.map(([n,Icon])=><button key={n} className={page===n?'active':''} onClick={()=>go(n)}><Icon size={17}/><span>{n}</span></button>)}</nav><div className="side-foot"><div className="avatar">{user.full_name?.[0]||'R'}</div><div><b>{user.full_name}</b><small>{user.role}</small></div><button className="iconbtn" onClick={()=>{localStorage.removeItem('rafi_token');setUser(null)}}><I.LogOut size={16}/></button></div></aside><main><header><div className="globalsearch"><I.Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search matters, evidence, authorities…"/><kbd>⌘ K</kbd></div><div className="headericons"><Pill tone="good"><I.ShieldCheck size={11}/> Reviewable AI</Pill><button className="iconbtn"><I.Bell size={18}/></button></div></header><div className="content">{content}</div><footer>© 2026 Rafi Legal Assist. All rights reserved. · AI-assisted work product requires professional review.</footer></main></div>
}


export default function App(){
  const [path,setPath]=useState(window.location.pathname || '/');
  useEffect(()=>{const h=()=>setPath(window.location.pathname || '/');window.addEventListener('popstate',h);return()=>window.removeEventListener('popstate',h)},[]);
  if(path.startsWith('/app')) return <WorkspaceApp/>;
  return <PublicSite path={path}/>;
}
